default_language_version:
  python: python3.10
repos:
  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black
        exclude: ^.*\b(migrations|settings)\b.*$
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args: ["--max-line-length=88"]
        exclude: ^.*\b(migrations|settings)\b.*/.*$
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--filter-files"]