version: '3.1'

services:
#   nginx:
#       image: nginx:1.17.10
#       container_name: nginx_SR01
#       ports:
#           - "80:80"
#       volumes:
#           - ./studyrun:/studyrun
#           - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
#       depends_on:
#           - web

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  api:
    build: .
    environment:
      - DATABASE_URL=postgres://postgres:postgres@localhost:5432/test_db"
    ports:
      - "8000:8000"
    volumes:
      - .:/Backend_Developer_Discovery
    command: bash -c "
          python developer_discover/manage.py makemigrations &&
          python developer_discover/manage.py migrate &&
          python developer_discover/manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  web:
    build: ../Frontend_Developer_Discovery
    ports:
      - "3000:3000"
    volumes:
      - ../Frontend_Developer_Discovery:/Frontend_Developer_Discovery
    command: npm start