version: '3.1'

services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  api:
    build: .
    environment:
      - DATABASE_URL=postgres://postgres:postgres@localhost:5432/test_db"
    ports:
      - "8000:8000"
    volumes:
      - .:/Backend_Developer_Discovery
    command: bash -c "
          python developer_discover/manage.py makemigrations &&
          python developer_discover/manage.py migrate &&
          python developer_discover/manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  web:
    build: ../Frontend_Developer_Discovery
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    volumes:
      - ../Frontend_Developer_Discovery:/Frontend_Developer_Discovery
    command: npm run dev
