version: '3.1'

services:
  nginx:
    restart: always
    image: nginx
    volumes:
      - ./etc/nginx/nginx-dev.conf:/etc/nginx/nginx.conf
      - ./etc/nginx/certs:/etc/nginx/certs
      # - ./etc/certbot/conf:/etc/letsencrypt
      # - ./etc/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    depends_on:
      - api
  
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  api:
    build: .
    restart: always
    environment:
      - DATABASE_URL=postgres://postgres:postgres@localhost:5432/test_db"
    ports:
      - "8000:8000"
    volumes:
      - ./developer_discover:/developer_discover
    command: bash -c "
          python developer_discover/manage.py db_connection &&
          python developer_discover/manage.py makemigrations &&
          python developer_discover/manage.py migrate &&
          python developer_discover/manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  web:
    build: ../Frontend_Developer_Discovery
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ../Frontend_Developer_Discovery:/Frontend_Developer_Discovery
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev
