[tool.black]
line-length = 120
include = '\.pyi?$'
exclude = ''' 
/(
    \.git
  | \.venv
  | \.github
  | README.md
  | Pipfile
  | Pipfile.lock
  | settings
  | migrations
  | developer_discover/developer_discover/*
)/
'''

[tool.isort]
profile = "black"
default_section = "THIRDPARTY"
known_django = "django"
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "DJANGO", "FIRSTPARTY", "LOCALFOLDER"]
skip_glob = ["*/migrations/*", "*/settings/*", "*/developer_discover/developer_discover/*"]
force_single_line = true