# Generated by Django 4.0.4 on 2022-11-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('basic', '기본')], default='', max_length=50)),
                ('image', models.ImageField(null=True, upload_to='image/%Y/%m/%d')),
                ('content', models.CharField(default='', max_length=1000)),
                ('answer_count', models.IntegerField(default=2)),
            ],
            options={
                'db_table': 'questions',
            },
        ),
    ]
