# Generated by Django 4.0.4 on 2022-07-03 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='Answer_count',
            new_name='answer_count',
        ),
    ]
