# Generated by Django 4.0.4 on 2022-07-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_answer_count_question_answer_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterModelTable(
            name='answer',
            table='answers',
        ),
    ]
