# Generated by Django 4.0.4 on 2022-10-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='category',
            field=models.CharField(choices=[('basic', '기본')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('basic', '기본')], default='', max_length=50),
        ),
    ]
