# Generated by Django 4.0.4 on 2023-04-15 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='introduction',
            field=models.TextField(default='', max_length=2048, null=True, verbose_name='소개'),
        ),
    ]
