# Generated by Django 4.0.4 on 2023-04-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='locations',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='위치'),
        ),
    ]
