# Generated by Django 4.0.4 on 2022-11-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('basic', '기본')], default='', max_length=50)),
                ('name', models.CharField(default='user_name', max_length=200)),
                ('score', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'scores',
            },
        ),
    ]
