# Generated by Django 4.0.4 on 2022-11-12 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='category',
            field=models.CharField(choices=[('basic', '기본'), ('language', '언어영역')], default='', max_length=50),
        ),
    ]
