# Generated by Django 4.0.4 on 2023-01-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='category',
            field=models.CharField(choices=[('basic', '기본'), ('language', '언어영역')], default='', max_length=50),
        ),
    ]
