# Generated by Django 4.0.4 on 2023-04-14 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(default='', max_length=512, verbose_name='제목'),
        ),
        migrations.AlterField(
            model_name='video',
            name='youtube_link',
            field=models.CharField(default='', max_length=2048, verbose_name='유튜브 링크'),
        ),
    ]
