# Generated by Django 4.0.4 on 2023-06-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_is_deleted_post_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='title', max_length=1024, verbose_name='제목'),
            preserve_default=False,
        ),
    ]
