name: deployment

on: workflow_dispatch

env:
  USER: github-action
  AWS_REGION: ap-northeast-2

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Configure AWS credential
        users: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: GIT Checkout Branch
        uses: actions/checkout@main

      - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@aaf69d68aa3fb14c1d5a6be9ac61fe15b48453a2
