name: deployment

on: workflow_dispatch

env:
  USER: github-action
  AWS_REGION: ap-northeast-2

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Configure AWS credential
        users: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: GIT Checkout Branch
        uses: actions/checkout@main

      - name: Code Deploy
        run: aws deploy create-deployment 
        --application-name EC2-S3-Deploy 
        --deployment-config-name CodeDeployDefault.OneAtATime 
        --deployment-group-name dev 
        --s3-location bucket=codesquad-deploy,bundleType=zip,key=server/build.zip
