name: SSH-deployment

on: workflow_dispatch

jobs:
  SSH:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run scripts in server
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          port: 22
          script: |
            cd /projects/Backend_Developer_Discovery
            git pull
            docker compose -f docker-compose-prod.yml up -d nginx api
            