name: test

on : push

jobs:
  linter:
    name: linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: rickstaa/action-black@v1
        with:
          black_args: ". --check --line-length 88"
      - uses: isort/isort-action@master
        with:
          configuration: "--profile black --check-only --diff --line-length 88"
  
  bulid:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
            python-version: '3.10'

      - name: Cache python packages
        uses: actions/cache@v2
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-pipenv-${{ hashFiles('Pipfile.lock') }}

      - name: Install dependencies
        run: |
          pip install --upgrade pip && pip install pipenv
          pipenv install --dev --ignore-pipfile
          pipenv --venv
          